/** Catalog of draggable component types: display metadata + simulation parameters. */
export const COMPONENTS = {
  client: {
    type: "client",
    label: "Client",
    icon: "⬡",
    color: "#6EE7B7",
    bg: "#064E3B",
    baseLatency: 0,
    capacity: Infinity,
    description: "User requests origin",
  },
  loadBalancer: {
    type: "loadBalancer",
    label: "Load Balancer",
    icon: "⚖",
    color: "#FCD34D",
    bg: "#78350F",
    baseLatency: 5,
    capacity: 10000,
    description: "Distributes traffic across servers",
  },
  server: {
    type: "server",
    label: "App Server",
    icon: "▣",
    color: "#93C5FD",
    bg: "#1E3A5F",
    baseLatency: 50,
    capacity: 1000,
    description: "Processes application logic",
  },
  cache: {
    type: "cache",
    label: "Cache",
    icon: "◈",
    color: "#F9A8D4",
    bg: "#500724",
    baseLatency: 5,
    capacity: 8000,
    description: "In-memory fast data store (Redis)",
  },
  database: {
    type: "database",
    label: "Database",
    icon: "◎",
    color: "#A78BFA",
    bg: "#2E1065",
    baseLatency: 200,
    capacity: 500,
    description: "Persistent data storage",
  },
  cdn: {
    type: "cdn",
    label: "CDN",
    icon: "◉",
    color: "#6EE7F7",
    bg: "#0C4A6E",
    baseLatency: 2,
    capacity: 50000,
    description: "Global content delivery network",
  },
  queue: {
    type: "queue",
    label: "Message Queue",
    icon: "≡",
    color: "#FBB06A",
    bg: "#7C2D12",
    baseLatency: 20,
    capacity: 20000,
    description: "Async message buffer (Kafka/RabbitMQ)",
  },
  microservice: {
    type: "microservice",
    label: "Microservice",
    icon: "⬡",
    color: "#86EFAC",
    bg: "#14532D",
    baseLatency: 40,
    capacity: 800,
    description: "Independent service unit",
  },
};
